config/routes.rb
Rails.application.routes.draw do
  
  get 'toppages/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content , presence: true, length: {maximum: 255}
  validates :status , presence: true, length: {maximum: 10}
  
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
  
  def require_user_logged_in
    unless logged_in?
     redirect_to login_url
    end
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to :root
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  
  before_action :correct_user, only: [:show, :destroy, :update, :edit]
  
  def index
    @tasks = current_user.tasks.page(params[:page]).per(5)
  end
  
  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    
    if(@task.save)
      flash[:success] = '課題の生成成功！'
      redirect_to @task
    else
      flash.now[:danger] = '課題が投稿されませんでした'
      render :new
    end
  end
  
  def update
    
    if(@task.update(task_params))
      flash[:success] = '課題の更新成功！'
      redirect_to @task
    else
      flash.now[:danger] = '課題が更新されませんでした'
      render :edit
      
    end
  end
  
  def edit
  end
  
  def destroy
    @task.destroy
    
    flash[:success] = '課題は正常に削除されました！'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  #strong parameter
  def task_params
    params.require(:task).permit(:content, :status, :user_id)
  end
  
  
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options= {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%=message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li> <%= link_to "新規課題の投稿", new_task_path  %></li>
            <li> <%= link_to "ログアウト", logout_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to "Signup", signup_path %></li>
            <li> <%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-ewuiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width-device-width, initial-scale=1">
    
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <%= render "layouts/navbar" %>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3" >
    <%= form_for(@task) do |f| %>
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :content, '課題'  %>
        <%= f.text_field :content ,class: "form-control" %>
        <%= f.label :status, '状態'   %>
        <%= f.text_field :status ,class: "form-control" %>
      </div>
  
      <%= f.submit '投稿', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %>作成課題編集ページ</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>自分がやるべきタスク一覧</h1>

<% if @tasks.any? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>課題内容</th>
      <th>状態</th>
    </tr>
  </thead>
  
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td> <%= link_to task.id , task %></td>
        <td> <%= task.content %> </td>
        <td> <%= task.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
    <%= paginate @tasks %>
</div>
<% end %>
<%= link_to '新しい課題の生成', new_task_path , class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>新規作成課題ページ</h1>
<%= render 'form', task: @task%>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> の課題詳細ページ</h1>

<h3> content:<%= @task.content  %> status: <%= @task.status  %> </h3>

<%= link_to 'この課題を編集する', edit_task_path(@task), class: "btn btn-default" %>
<%= link_to '課題の削除をする', @task, method: :delete, data: { confirm: '本当に削除しますか?'} , class: "btn btn-danger" %> 

app/views/toppages/index.html.erb
<% if logged_in? %>
  <h1>自分がやるべきタスク一覧</h1>

  <% if @tasks.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>課題内容</th>
          <th>状態</th>
        </tr>
      </thead>
  
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td> <%= link_to task.id , task %></td>
            <td> <%= task.content %> </td>
            <td> <%= task.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
        <%= paginate @tasks %>
    </div>
  <% end %>
  <%= link_to '新しい課題の生成', new_task_path , class: "btn btn-primary" %>
  <p>ログインに完了ユーザ:<%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to tasklist!</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign Up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>